# version: '3.8'

# volumes: 
#   grafana_data: {}

# networks:
#   front-tier:
#   back-tier:

# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     ports:
#       - "5432:5432"
#     networks:
#       - back-tier

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - "8080:8080"
#     networks:
#       - back-tier
#       - front-tier  

#   grafana:
#     image: grafana/grafana
#     user: "472"
#     ports:
#       - "3000:3000"
#     volumes:
#       - /workspaces/mlops_zoomcamp_2024/05-monitoring/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
#       - /workspaces/mlops_zoomcamp_2024/05-monitoring/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
#       - /workspaces/mlops_zoomcamp_2024/05-monitoring/dashboards:/opt/grafana/dashboards
#     networks:
#       - back-tier
#       - front-tier
#     restart: always

version: '3.8'

volumes: 
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier  

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/opt/grafana/dashboards
    networks:
      - back-tier
      - front-tier
    restart: always